//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditPressRu.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtiklesIndexes
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string HrefToArtikle { get; set; }
        public int PriznakArtiklActNews { get; set; }
        public bool Publish { get; set; }
        public string Autor { get; set; }
        public Nullable<System.DateTime> DatePublish { get; set; }
    }
}
