//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditPressRu.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPrestige_Products
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Artikul { get; set; }
        public string Price { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> FreeCnt { get; set; }
        public string Color { get; set; }
        public string Material { get; set; }
        public string Size { get; set; }
        public string PrezervatCnt { get; set; }
        public string PrezervatWeight { get; set; }
        public string PrezervatVolume { get; set; }
        public string Nanesenie { get; set; }
        public string Descript { get; set; }
        public string Href { get; set; }
    }
}
