//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditPressRu.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPrestige_Images
    {
        public int Id { get; set; }
        public int ProdId { get; set; }
        public string Image { get; set; }
        public bool Main { get; set; }
        public string Small { get; set; }
    }
}
