//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditPressRu.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EbazarBase_CatIntercept
    {
        public int Id { get; set; }
        public Nullable<int> EbId { get; set; }
        public Nullable<int> EbParentId { get; set; }
        public string EbName { get; set; }
        public string EditName { get; set; }
        public Nullable<int> EditParentId { get; set; }
        public Nullable<int> EditId { get; set; }
    }
}
