//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditPressRu.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EklekticBase_CatIntercept
    {
        public int Id { get; set; }
        public Nullable<System.Guid> EklectCatId { get; set; }
        public string EklectName { get; set; }
        public string EditName { get; set; }
        public Nullable<int> EditCatId { get; set; }
    }
}
