//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditPressRu.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftBase_Catalog
    {
        public int id { get; set; }
        public Nullable<int> parent_page_id { get; set; }
        public Nullable<int> page_id { get; set; }
        public string name { get; set; }
        public string uri { get; set; }
    }
}
