//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditPressRu.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftBase_Products
    {
        public int product_id { get; set; }
        public Nullable<int> group { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string product_size { get; set; }
        public string matherial { get; set; }
        public string small_image { get; set; }
        public string big_image { get; set; }
        public string super_big_image { get; set; }
        public string content { get; set; }
        public string status { get; set; }
        public string brand { get; set; }
        public string weight { get; set; }
        public string price_price { get; set; }
        public string price_value { get; set; }
        public string price_currency { get; set; }
        public string price_name { get; set; }
        public Nullable<int> amount_pack { get; set; }
        public string weight_pack { get; set; }
        public string volume_pack { get; set; }
        public string sizex_pack { get; set; }
        public string sizey_pack { get; set; }
        public string sizez_pack { get; set; }
    }
}
