//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditPressRu.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftBase_Attachments
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public Nullable<bool> meaning { get; set; }
        public string file { get; set; }
        public string image { get; set; }
        public string name { get; set; }
    }
}
