//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditPressRu.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftBase_GiftEditCatIntersept
    {
        public int Id { get; set; }
        public int editId { get; set; }
        public int editParentId { get; set; }
        public string editName { get; set; }
        public int giftId { get; set; }
        public Nullable<int> gift_parent_page_id { get; set; }
        public Nullable<int> gift_page_id { get; set; }
        public string giftName { get; set; }
        public string gift_uri { get; set; }
    }
}
