//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditPressRu.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class KP_Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KP_Store()
        {
            this.Kp_Store_dop = new HashSet<Kp_Store_dop>();
        }
    
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public string KpNumber { get; set; }
        public string KPpath { get; set; }
        public string KpImg { get; set; }
        public string Publish { get; set; }
        public Nullable<int> MarkUp { get; set; }
        public Nullable<int> Sale { get; set; }
        public string Currency { get; set; }
        public decimal СurrencyValue { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string AlternateContacts { get; set; }
        public string KpForeColor { get; set; }
        public bool UserP { get; set; }
        public bool ArticleP { get; set; }
        public bool CharacterP { get; set; }
        public bool DescrP { get; set; }
        public bool SumTirageP { get; set; }
        public bool TotalP { get; set; }
        public System.DateTime DateDoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kp_Store_dop> Kp_Store_dop { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
