//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditPressRu.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makety
    {
        public int Id { get; set; }
        public int ProdId { get; set; }
        public string FilePath { get; set; }
        public string Ext { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
