//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditPressRu.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oasis_Products
    {
        public string id { get; set; }
        public string article { get; set; }
        public string parent_color_id { get; set; }
        public string parent_size_id { get; set; }
        public string name { get; set; }
        public string full_name { get; set; }
        public string size { get; set; }
        public string weight { get; set; }
        public string complectnost { get; set; }
        public string price { get; set; }
        public string discount_group_id { get; set; }
        public string brand_id { get; set; }
        public string kit_id { get; set; }
        public Nullable<bool> is_virtual { get; set; }
        public Nullable<int> rating { get; set; }
        public string description { get; set; }
        public string brand { get; set; }
        public string branding { get; set; }
        public string cdr { get; set; }
        public string group_id { get; set; }
        public string video_id { get; set; }
        public Nullable<bool> is_export_allowed { get; set; }
        public Nullable<bool> is_visible { get; set; }
        public string color_group_id { get; set; }
        public string parent_volume_id { get; set; }
        public string parent_gender_id { get; set; }
        public Nullable<bool> is_on_order { get; set; }
        public string old_price { get; set; }
        public Nullable<bool> is_high { get; set; }
        public Nullable<int> size_sort { get; set; }
        public string parent_id { get; set; }
        public Nullable<int> type_id { get; set; }
        public string branding_option { get; set; }
        public string article_base { get; set; }
        public Nullable<bool> is_vip { get; set; }
        public Nullable<int> provider_type_id { get; set; }
        public Nullable<bool> is_stopped { get; set; }
        public string main_category { get; set; }
        public string discount_price { get; set; }
        public string volume { get; set; }
        public bool hit { get; set; }
    }
}
