//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditPressRu.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oasis_Packages
    {
        public int pakage_id { get; set; }
        public string oasisId { get; set; }
        public string type { get; set; }
        public string description { get; set; }
        public string size { get; set; }
        public string weight { get; set; }
        public string amount { get; set; }
        public string volume { get; set; }
        public Nullable<bool> is_main { get; set; }
    }
}
