//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditPressRu.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oasis_ProdImages
    {
        public int Id { get; set; }
        public string OasisId { get; set; }
        public string big { get; set; }
        public string superbig { get; set; }
        public string thumbnail { get; set; }
        public Nullable<int> updated_at { get; set; }
    }
}
