//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditPressRu.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oasis_Categories
    {
        public int id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> root { get; set; }
        public Nullable<int> lft { get; set; }
        public Nullable<int> rgt { get; set; }
        public Nullable<int> level { get; set; }
        public string slug { get; set; }
        public string name { get; set; }
        public string path { get; set; }
    }
}
