//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditPressRu.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web.Mvc;

    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Makety = new HashSet<Makety>();
            this.ProdImages = new HashSet<ProdImages>();
            this.ProdInCategory = new HashSet<ProdInCategory>();
            this.Prods_Colors = new HashSet<Prods_Colors>();
            this.Prods_Materials = new HashSet<Prods_Materials>();
            this.Prods_Nanesenie = new HashSet<Prods_Nanesenie>();
            this.ProdVideos = new HashSet<ProdVideos>();
        }
    
        public int Id { get; set; }
        public Nullable<int> VendorId_int { get; set; }
        public string VendorId_str { get; set; }
        public int VendorId { get; set; }

        [DisplayName("Показывать товар на сайте")]
        public bool Publish { get; set; }
        
        [DisplayName("Артикул на сайте")]
        public string Article { get; set; }
        
        [DisplayName("Артикул для менеджера")]
        public string OldArticle { get; set; }

        [DisplayName("Расширенное наименование товара, добавлятьсюда артикул, цвет и другие атрибуты поиска! - по этой колонке осуществляется поиск ")]
        public string Name { get; set; }
        
        [DisplayName("Краткое наименование товара - выводится в карточке на сайте")]
        public string ShName { get; set; }

        [AllowHtml]
        [DisplayName("Описание товара")]
        public string Descript { get; set; }

        [DisplayName("Описание в метатегах - сюда короткие описание товара для поискового робота")]
        public string MetaDescript { get; set; }

        [DisplayName("Сюда ключевые слова и фразы")]
        public string MetaKeyWords { get; set; }

        [DisplayName("Сюда пишем: Купить+краткое наименование+ под нанесение печати")]
        public string Title { get; set; }

        [DisplayName("Описание в слайдер")]
        public string DusheUgodno { get; set; }

        [DisplayName("Бренд")]
        public Nullable<int> BrandId { get; set; }

        [DisplayName("Размер флешки")]
        public string Flash_size { get; set; }

        [DisplayName("Линейный рзмер")]
        public string Size { get; set; }

        [DisplayName("Объем")]
        public string Volume { get; set; }
        
        [DisplayName("Количество в упаковке")]
        public string Amount { get; set; }

        [DisplayName("Вес")]
        public string Weight { get; set; }

        [DisplayName("Атрибут - пока не задействован")]
        public string Atribut { get; set; }

        [DisplayName("Упаковка")]
        public string Preservative { get; set; }
        
        [DisplayName("Рейтинг")]
        public int Rank { get; set; }

        [DisplayName("Сорт")]
        public decimal Sort { get; set; }

        [DisplayName("Цена")]
        public decimal Price { get; set; }

        [DisplayName("Цена оптовая")]
        public Nullable<decimal> Price_opt { get; set; }
        
        [DisplayName("Цена старая")]
        public Nullable<decimal> Price_old { get; set; }

        [DisplayName("Размер скидки")]
        public string SaleSize { get; set; }

        [DisplayName("Признак что товар со скидкой")]
        public bool Sale { get; set; }

        [DisplayName("Признак товар хит сезона")]
        public bool Hit { get; set; }

        [DisplayName("Признак товар новинка")]
        public bool New { get; set; }

        [DisplayName("Признак товар из Китая")]
        public bool China { get; set; }

        [DisplayName("Признак топ продаж")]
        public bool TopSales { get; set; }

        [DisplayName("Признак - в наличии")]
        public Nullable<bool> Nalichie { get; set; }

        [DisplayName("Оценка рейтинга")]
        public Nullable<int> Rating { get; set; }

        [DisplayName("Количество в магазине")]
        public Nullable<int> Stock { get; set; }

        [DisplayName("Количество на удаленном складе")]
        public Nullable<int> Stock_remote { get; set; }

        [DisplayName("Количество в пути")]
        public Nullable<int> Stock_transit { get; set; }

        [DisplayName("Количество в Москве")]
        public Nullable<int> Stock_local { get; set; }

        [DisplayName("Зарезервировано")]
        public Nullable<int> Reserve { get; set; }

        [DisplayName("Зарезервировано на удаленном складе")]
        public Nullable<int> Reserve_remote { get; set; }

        [DisplayName("Зарезервировано в пути")]
        public Nullable<int> Reserve_transit { get; set; }

        [DisplayName("Зарезервировано в Москве")]
        public Nullable<int> Reserve_local { get; set; }

        [DisplayName("Размер скидки")]
        public string Discount_group_id { get; set; }

        [DisplayName("Статус загруженного товара")]
        public Nullable<int> StatPlaceId { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual Brands Brands { get; set; }
        public virtual GroupColorProducts GroupColorProducts { get; set; }
        public virtual GroupSizeProducts GroupSizeProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Makety> Makety { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdImages> ProdImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdInCategory> ProdInCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prods_Colors> Prods_Colors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prods_Materials> Prods_Materials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prods_Nanesenie> Prods_Nanesenie { get; set; }
        public virtual Vendors Vendors { get; set; }
        public virtual Vendors Vendors1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdVideos> ProdVideos { get; set; }
    }
}
