//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditPressRu.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Redirect
    {
        public int Id { get; set; }
        public Nullable<System.Guid> OldProdId { get; set; }
        public Nullable<int> OldCatId { get; set; }
        public Nullable<int> OldNum { get; set; }
        public Nullable<int> OldSubCatId { get; set; }
        public string OldCatName { get; set; }
        public string OldSubCatName { get; set; }
        public string OldProdName { get; set; }
        public string OldIink { get; set; }
        public Nullable<int> CatId { get; set; }
        public string CatName { get; set; }
        public Nullable<int> ProdId { get; set; }
        public string ProdName { get; set; }
        public string NewLink { get; set; }
        public Nullable<int> Num { get; set; }
    }
}
