//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditPressRu.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShluseForVendors
    {
        public int Id { get; set; }
        public int VendorId { get; set; }
        public Nullable<int> VendorIntId { get; set; }
        public string VendorStrId { get; set; }
        public string Article { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceOpt { get; set; }
        public Nullable<decimal> PriceOld { get; set; }
        public string DiscountGroupId { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> StockLocal { get; set; }
        public Nullable<int> StockRemote { get; set; }
        public Nullable<int> StockTransit { get; set; }
        public Nullable<int> Reserve { get; set; }
        public Nullable<int> ReserveLocal { get; set; }
        public Nullable<int> ReserveTransit { get; set; }
        public Nullable<int> ReserveRemote { get; set; }
        public string DateUpdate { get; set; }
        public string Comment { get; set; }
    }
}
