//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditPressRu.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfileDetails
    {
        public int UserProfileDetailsID { get; set; }
        public int UserID { get; set; }
        public int DiscountID { get; set; }
        public string ShipmentAddress { get; set; }
        public string OrgName { get; set; }
        public string INN { get; set; }
        public string FIO { get; set; }
        public string Phone { get; set; }
        public string email { get; set; }
        public string Site { get; set; }
        public string LogoImg { get; set; }
    
        public virtual Discounts Discounts { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
